services:
  # TaniVerse Application (Laravel 12/13)
  taniverse_app:
    build: 
      context: ./php
      dockerfile: Dockerfile
    image: taniverse_platform:8.4
    container_name: taniverse_core
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - taniverse_db
    networks:
      - taniverse-network

  # TaniVerse Web Server (Nginx) - Pintu Akses Utama
  taniverse_web:
    image: nginx:alpine
    container_name: taniverse_nginx
    restart: unless-stopped
    ports:
      - "80:80"   # Akses web lewat port 80
      - "443:443" # Persiapan jika nanti pakai SSL/HTTPS
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - taniverse_app
    networks:
      - taniverse-network

  # TaniVerse Database Engine (PostgreSQL)
  taniverse_db:
    image: postgres:16-alpine
    container_name: taniverse_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-taniverse_db}
      POSTGRES_USER: ${DB_USER:-djambred}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-p455w0rd1!.}
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql_data:/var/lib/postgresql/data
    networks:
      - taniverse-network

networks:
  taniverse-network:
    name: taniverse_mesh
    driver: bridge